get_albums:
    path:     /albums
    defaults: { _controller: PayeverTestBundle:Album:getAlbums }
    
get_albums_by_images_count:
    path:     /albums/count_images/{amount}
    defaults: { _controller: PayeverTestBundle:Album:getByImagesCount }
    
get_album_images_paged:
    path:     /album/{albumId}/page/{page}
    defaults: { _controller: PayeverTestBundle:Album:getAlbumImages }

get_album_images:
    path:     /album/{albumId}
    defaults: { _controller: PayeverTestBundle:Album:getAlbumImages }    
