services:

    payever.album_manager:
        class: Payever\TestBundle\Services\AlbumManagerService
        arguments:
            doctrine:   "@doctrine.orm.entity_manager"
            paginator:  "@knp_paginator"
            serializer: "@serializer"
            
    payever.image_manager:
        class: Payever\TestBundle\Services\ImageManagerService
        arguments:
            doctrine: "@doctrine.orm.entity_manager"